### ISSUE TITLE
Better error message when Forecast token has expired

### ISSUE THREAD

**Issue by stpe** [stpe/harvest-forecast-slack-checkin#1]
Currently the API wrapper does deal really well with expired tokens. TODO to myself: do something about it.

Also, fail gracefully if API returns nothing.

**Comment by steve-ross** [comment]
yeah this just killed me... FYI the error I got was:

```
TypeError: Cannot read property 'forEach' of undefined
    at module.exports.data (/Users/sross/harvest-forecast-slack-checkin/app/lib/lookup.js:6:7)
    at /Users/sross/harvest-forecast-slack-checkin/app/checkin.js:37:18
    at process._tickCallback (node.js:369:9)
```

**Comment by stpe** [comment]
I've now implemented a check that in case of no data (typically because an expired auth token) a DM sent to a user (`SLACK_FORECAST_ADMIN`).
