### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by jacopocolo** [stpe/harvest-forecast-slack-checkin#4]
I’m getting a [TypeError: Cannot read property 'name' of undefined] when I try to run the integration locally with npm start. When I run npm test the test is passed on all 9 steps but then I can’t get it to post on Slack.

**Comment by stpe** [comment]
I've implemented some check to make sure data is retrieved successfully from Forecast as well as a more graceful fallback where this error may happen. If this isn't solved since long, please try again with the most recent version and see if you still get this error. Thanks!
